### ISSUE TITLE
PRACTICA FINAL DE HILOS

### ISSUE THREAD

**Issue by IsaacCS1** [SistemasTecTlaxiaco/practica-final-de-hilos-tadp-isag#2]
[PRACTICA_7.pdf](https://github.com/SistemasTecTlaxiaco/practica-final-de-hilos-tadp-isag/files/8579823/PRACTICA_7.pdf)

**Comment by IrvingFernand0** [comment]
Calificación: 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
